#!/bin/bash
# Session closing checklist for Pulsar4x. Runs when Claude stops generating.

echo ""
echo "════════════════════════════════════════════════════"
echo "PULSAR4X SESSION CLOSING CHECKLIST"
echo "════════════════════════════════════════════════════"
echo ""
echo "  IF CODE WAS CHANGED this session:"
echo "  ─────────────────────────────────"
echo "  Steps 1-2 run on DEVELOPER'S WINDOWS MACHINE in PowerShell:"
echo "    1. git pull origin claude/amazing-clarke-7s118n"
echo "    2. dotnet build Pulsar4X/Pulsar4X.sln"
echo "    3. dotnet test Pulsar4X/Pulsar4X.Tests/Pulsar4X.Tests.csproj"
echo "    (paste any errors back so Claude can fix before pushing)"
echo ""
echo "  Steps 4-6 happen here in the cloud session:"
echo "    4. For each file in git diff --name-only:"
echo "         → if it belongs to a subsystem with a CLAUDE.md,"
echo "           that CLAUDE.md must also be in the diff"
echo "    5. If phase progress was made, update PLAN.md + SESSION_STATE.md"
echo "    6. git commit with descriptive message"
echo "    7. git push -u origin claude/amazing-clarke-7s118n"
echo ""
echo "  IF ONLY DOCS WERE CHANGED this session:"
echo "  ─────────────────────────────────────────"
echo "  Skip build/test. Still commit and push."
echo ""
echo "  HARD STOPS:"
echo "    • Failing build  → do not push"
echo "    • Failing tests  → do not push (unless pre-existing failure,"
echo "      confirm with developer running: git stash + retest)"
echo "    • async void exception swallowing → add a test to catch it"
echo "════════════════════════════════════════════════════"
