
// This file has been generated by the GUI designer. Do not modify.
namespace Pulsar4X.GTKForms
{
	public partial class MainWindowGTK
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action Pulsar4XAction;
		private global::Gtk.VBox vbox5;
		private global::Gtk.MenuBar menubar2;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Label label7;
		private global::Pulsar4X.GTKForms.Controls.SystemDisplayGTK systemdisplaygtk1;
		private global::Gtk.Label label8;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pulsar4X.GTKForms.MainWindowGTK
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.Pulsar4XAction = new global::Gtk.Action ("Pulsar4XAction", global::Mono.Unix.Catalog.GetString ("Pulsar4X"), null, null);
			this.Pulsar4XAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pulsar4X");
			w1.Add (this.Pulsar4XAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Pulsar4X.GTKForms.MainWindowGTK";
			this.Title = global::Mono.Unix.Catalog.GetString ("Pulsar4X");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultHeight = 600;
			// Container child Pulsar4X.GTKForms.MainWindowGTK.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='Pulsar4XAction' action='Pulsar4XAction'/></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox5.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.notebook1.Add (this.alignment1);
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("SystemMap");
			this.notebook1.SetTabLabel (this.alignment1, this.label7);
			this.label7.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.systemdisplaygtk1 = new global::Pulsar4X.GTKForms.Controls.SystemDisplayGTK ();
			this.systemdisplaygtk1.Events = ((global::Gdk.EventMask)(256));
			this.systemdisplaygtk1.Name = "systemdisplaygtk1";
			this.notebook1.Add (this.systemdisplaygtk1);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.systemdisplaygtk1]));
			w4.Position = 1;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("SystemDisplay");
			this.notebook1.SetTabLabel (this.systemdisplaygtk1, this.label8);
			this.label8.ShowAll ();
			this.vbox5.Add (this.notebook1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.notebook1]));
			w5.Position = 1;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1038;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
